version: '3.7'
services:

  client:
    container_name: facebook-clone_client
    restart: unless-stopped
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - ./client/src/:/app/src
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - server
      - database

  server:
    container_name: facebook-clone_server
    image: maven:3.8.5-openjdk-17-slim
    command: mvn spring-boot:run
    ports:
      - '8080:8080'
    volumes:
      - ./server/:/server/src/main:rw
    working_dir: /server/src/main

  database:
    container_name: facebook-clone_db
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=facebook_db


volumes:
  data: